version: '3.9'


services:
  web:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_TAG}:${IMAGE_VERSION}
    build: 
      context: fast_api
      dockerfile: Dockerfile
      args:
        - PORTT=${BACKEND_PORT}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    command: uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    volumes:
      - ./fast_api/codebase/:/usr/src/app