version: '3.9'

services:
  nginx:
    container_name: nginx
    image: replaced-nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/usr/share/nginx/html/